motd:
  first:
  - "&cHi there"
  - "&aRandom &7player"
  second:
  - "&bOh hi there!"
  - "&3%player% :)"
# If a player has joined before, should the plugin do its best to display a MOTD that contains the %player% placeholder?
force-personalized-motd-if-available: true
# If a player has never joined before, should the plugin only show messages that does NOT contain the %player% placeholder?
force-guest-message-for-guests: true
# If a player isn't found but a %player% placeholder is used in the message the player receives.
guest-placeholder: "Guest"
# Should the plugin randomly choose a server icon from the 'icons' folder? NOTE: Icons must be 64x64 pixels and in the .png format!
random-server-icon: false
# Force icon for new users. None to disable
new-users-icon: none
# Force icon for returning users. None to disable
returning-users-icon: none