motd:
  first:
  - "&cHi there"
  - "&aRandom &7player"
  second:
  - "&bOh hi there!"
  - "&3%player% :)"
# If a player has joined before, should the plugin do its best to display a MOTD that contains the %player% placeholder?
force-personalized-motd-if-available: true
# If a player has never joined before, should the plugin only show messages that does NOT contain the %player% placeholder?
force-guest-message-for-guests: true
# If a player isn't found but a %player% placeholder is used in the message the player receives.
guest-placeholder: "Guest"
# Should the plugin randomly choose a server icon from the 'icons' folder? NOTE: Icons must be 64x64 pixels and in the .png format!
random-server-icon: false

### The options below this is recommended to be left as default, as they can be confusing
### If you wish to have random icons, specific icons for returning users
### and specific icon for guests then the settings below are for you.

# Force icon for new users. None to disable
new-users-icon: none
# Remove the "new-users-icon" from the pool of random icons for returning users, if a "returning-users-icon" isn't specified?
remove-new-users-icon-from-random-pool: true
# Force icon for returning users. None to disable
returning-users-icon: none
# Remove the "returning-users-icon" from the pool of random icons for new users, if a "new-users-icon" isn't specified?
remove-returning-users-icon-from-random-pool: true